name: Download BAKOM Data
  uses: wow-actions/download-upload@bc8411c3dfcb62fee64632638e109283203abbda
  with:
    GITHUB_TOKEN: ${{ secrets.GHAPI }}
    # The file url to download
    url: https://data.geo.admin.ch/ch.bakom.standorte-mobilfunkanlagen/standorte-mobilfunkanlagen/standorte-mobilfunkanlagen_2056.json
    # The file name to save
    filename: # FILENAME=bakom-raw-$(date +'%Y-%m-%d').json
    # The dir path to save the file
    dir: # optional
    # Commit message when update the file
    commit_message: # optional, default is chore: update file [skip ci]
