name: Download BAKOM Data

on:
  workflow_dispatch:  # Allows manual triggering via GitHub UI
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 UTC on the 1st of every month

permissions:
  contents: write  # Grants write access for pushing changes

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set filename with current date
        run: echo "FILENAME=bakom-raw-$(date +'%Y-%m-%d').json" >> $GITHUB_ENV

      - name: Download BAKOM JSON
        run: |
          mkdir -p data
          curl -sSL https://data.geo.admin.ch/ch.bakom.standorte-mobilfunkanlagen/standorte-mobilfunkanlagen/standorte-mobilfunkanlagen_2056.json -o "data/${FILENAME}"
      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add data/${FILENAME}
          git commit -m "chore: add BAKOM data ${{ env.FILENAME }} [skip ci]" || echo "No changes to commit"
          git pull --rebase 
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GHAPI }}
